<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <PackageId>TypedItem</PackageId>
        <Title>A set of CosmosDB extension to managed typed container items</Title>
        <Authors>Michel Perfetti</Authors>
        <RepositoryUrl>https://github.com/miiitch/TypedItem</RepositoryUrl>
        <PackageTags>CosmosDB c# csharp dotnet .net</PackageTags>
        <PackageProjectUrl>https://github.com/miiitch/TypedItem</PackageProjectUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.59.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\..\README.md" Pack="true" PackagePath="\" />
      <None Include="..\..\..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
